using System;

namespace ContextManager.API.Models
{
    /// represents a user's session plan for a specific date, generated by the AI
    public class SessionPlan
    {
        public Guid Id { get; set; }
        public Guid UserId { get; set; }
        public DateTime PlanDate { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime? LastModifiedAt { get; set; }
        public bool IsCustomized { get; set; }
        public User User { get; set; } = null!;
        public ICollection<SessionPlanItem> Items { get; set; } = new List<SessionPlanItem>();
    }
    
    /// represents a single task item within a session plan
    public class SessionPlanItem
    {
        public Guid Id { get; set; }
        public Guid SessionPlanId { get; set; }
        public Guid TaskId { get; set; }
        public int Order { get; set; }
        public int GroupNumber { get; set; }
        public string Reasoning { get; set; } = string.Empty;
        public SessionPlan SessionPlan { get; set; } = null!;
        public Task Task { get; set; } = null!;
    }
}

